### PR TITLE
Issue12

### LINKED ISSUE #15: Daemon
In order to restrict access to authentication key (#11) , put backend interface inside a daemon (or something similar) run from the admin user (see #5, #1), and let authentication key have read access only from the admin user and process transactions only for users present in the user database/users that can authenticate themselves using the card number. Possibly also abstract away the user database access into this daemon, so that user database can be directly readable only from the admin user.

kryssgui (user) -> kryssd/ragno (admin) -> ufs

Need a client interface on the kryssgui side. Supported communication should more or less be the functionality listed in #12. DBus might be a possibility for communication if this is well-defined across different user processes.

### PR DESCRIPTION
**Pull request by bjorgan**
Solves mainly issue #12, but also the majority of work in #15 (should not close #15 yet, however, due to some remaining details).

Defines an abstract interface for processing transactions. Transactions are pushed through DBus to an external daemon, to be run as a separate user. The daemon is started automatically by DBus when needed.

Also added test environment, one full integration test for the daemon client, and two simple testcases for the card reader.

### CODE REVIEW

**Comment by oyvkar** [comment]
Builds successfully, but fails 1/2 tests. 

According to bjorgan the test fails because the dbus config file for the daemon is not present. 

Otherwise the code looks tidy and is well documented.

**Comment by bjorgan** [comment]
Since the tests do not make it clear enough what the problem actually was, I'll add... more tests. These tests are a bit problematic since they test the full, integrated system, and is more of a verification of a correct system setup than it verifies pieces of the code. Since the DBus setup itself is a bit challenging, I think we should let the tests remain, however, since they will help us in verifying the full system.

`make install` usually has to be run with admin rights since it by default installs to system-wide paths, but I'll make it more clear in the README.

**Comment by bjorgan** [comment]
I've updated the README (eea78bb5f608fcf494c942e7d3eb7fe603711c79), added a more verbose message in the signal timeout test (70fea20439c877c2102dbee9c475c2b95131f2fb), renamed the test to something more verbose and specific to what's actually tested and added a explicit test for correct DBus setup (bfc096f30de1e27eb936e9a97cedbce898382bc8) (minor corrections in subsequent commits).

**Comment by oyvkar** [comment]
Changes verified by corrupting newly installed dbus config by deleting one of the configuration files (sudo rm /etc/dbus-1/system.d/org.digcross.daemonconnection.conf) and running test "make test" along with ctest -V for detailed output.

**Pull request merged**
